export const FORK_DESKTOP_IDENTITY = {
  baseName: "V2 Code",
  stableDisplayName: "V2 Code",
  nightlyDisplayName: "V2 Code (Nightly)",
  devDisplayName: "V2 Code (Dev)",
  appId: "com.vishalharidas.v2code",
  devAppId: "com.vishalharidas.v2code.dev",
  artifactName: "V2-Code-${version}-${arch}.${ext}",
  executableName: "v2code",
  linuxDesktopEntryName: "v2code.desktop",
  devLinuxDesktopEntryName: "v2code-dev.desktop",
  linuxWmClass: "v2code",
  devLinuxWmClass: "v2code-dev",
  t3HomeDirName: "fork",
  stateDirName: "userdata",
  devStateDirName: "dev",
  userDataDirName: "v2code",
  devUserDataDirName: "v2code-dev",
  legacyUserDataDirName: "V2 Code",
  devLegacyUserDataDirName: "V2 Code (Dev)",
  enableAutoUpdates: false,
} as const;
