export const FORK_DESKTOP_IDENTITY = {
  baseName: "T3 Code Fork",
  stableDisplayName: "T3 Code Fork",
  nightlyDisplayName: "T3 Code Fork (Nightly)",
  devDisplayName: "T3 Code Fork (Dev)",
  appId: "com.vishalharidas.t3codefork",
  devAppId: "com.vishalharidas.t3codefork.dev",
  artifactName: "T3-Code-Fork-${version}-${arch}.${ext}",
  executableName: "t3code-fork",
  linuxDesktopEntryName: "t3code-fork.desktop",
  devLinuxDesktopEntryName: "t3code-fork-dev.desktop",
  linuxWmClass: "t3code-fork",
  devLinuxWmClass: "t3code-fork-dev",
  t3HomeDirName: "fork",
  stateDirName: "userdata",
  devStateDirName: "dev",
  userDataDirName: "t3code-fork",
  devUserDataDirName: "t3code-fork-dev",
  legacyUserDataDirName: "T3 Code Fork",
  devLegacyUserDataDirName: "T3 Code Fork (Dev)",
  enableAutoUpdates: false,
} as const;
